# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('registered_timestamp', models.DateTimeField(auto_now_add=True)),
                ('year', models.DateField(auto_now_add=True)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
    ]
