# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 20:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Student_Enrollment_Class',
            field=models.CharField(choices=[('FR', 'Fresher'), ('CONT', 'Continuing'), ('GRAD', 'Graduating')], default=datetime.datetime(2016, 9, 22, 20, 22, 45, 669517, tzinfo=utc), max_length=4),
            preserve_default=False,
        ),
    ]
