# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_student_student_enrollment_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('BIT', 'Bachelor of Information Technology'), ('BCS', 'Bachelor of Computer Science'), ('BPLM', 'Bachelor of Procument and Logistics Management'), ('BES', 'Bachelor of Education Social Development')], default=datetime.datetime(2016, 9, 22, 21, 12, 7, 448904, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(choices=[('SBA', 'School of Business Administration'), ('SCIAD', 'School of Industry Art and Design'), ('SLAW', 'School of Law'), ('SCOS', 'School of Social Sciences'), ('SHES', 'School of Humanities Education and Social Development')], default=datetime.datetime(2016, 9, 22, 21, 12, 23, 258770, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
